SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Schrattenholz\CallToActions\CallToActionsExtension
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Schrattenholz\CallToActions\CallToActionsExtension